### ISSUE TITLE
LoadBalancers array needs emptied on master machine

### ISSUE THREAD

**Issue by cuppett** [eformat/sno-for-100#16]
Noticed this Event go by on the log:

sno-1-6jxkf-master-0
(combined from similar events): sno-1-6jxkf-master-0: reconciler failed to Update machine: failed to updated update load balancers: LoadBalancerNotFound: Load balancers '[sno-1-6jxkf-int, sno-1-6jxkf-ext]' not found status code: 400, request id: 32db87a0-867d-454c-ae42-5e9680bb7836

In the Machine for the master, there's an array similar to this:

      loadBalancers:
        - name: sno-1-6jxkf-int
          type: network
        - name: sno-1-6jxkf-ext
          type: network

Those get whacked during conversion. It'll need updated/emptied like this:
          
        loadBalancers: []

**Comment by eformat** [comment]
thanks Steve
fixed with https://github.com/eformat/sno-for-100/commit/6090ab8777753ef9842311844d8a0345f3c664f4
