### ISSUE TITLE
Add the ability to use Lets encrypt on SNO

### ISSUE THREAD

**Issue by rafaeltuelho** [eformat/sno-for-100#18]
Something like is described here: https://ksingh7.medium.com/lets-automate-let-s-encrypt-tls-certs-for-openshift-4-211d6c081875

**Comment by eformat** [comment]
hi .. there are so many day#2 enhancements post install .. i have started to capture my favorites in the doc

https://github.com/eformat/sno-for-100#day2-enhancements

might be good to add these as optional automation though, rather than in the base install.
