### ISSUE TITLE
Elastic IPs attempted to be removed too soon

### ISSUE THREAD

**Issue by cuppett** [eformat/sno-for-100#5]
We probably need to wait for NAT GW to delete  completely (openshift-install destroy cluster has similar mechanism.)

Got this error running the script:

```
An error occurred (AuthFailure) when calling the ReleaseAddress operation: You do not have permission to access the specified resource.
🕱Failed - could not release eip 3.15.101.139 eipalloc-0018453cac7b2f9f6 ?
```

I think the permission message is a red herring. My user does. I believe the script didn't wait long enough for the NAT GW to be completely gone/deleted. I deleted them manually after a bit and re-ran the script to completion.

**Comment by eformat** [comment]
yeah .. i noticed this one as well .. rerun script and it works ok ... not sure WHY this is so ...

**Comment by cuppett** [comment]
The API call returns immediately, but the NAT GW deletes async and the EIP
can't be released until it is totally gone. (I wish they auto released on
delete. )

**Comment by eformat** [comment]
ah yup .. of course .. i will maybe add check for natgw removal before eip removed or a simple retry in that step

**Comment by eformat** [comment]
ok .. so i have added in a wait_for_nat_gateway_delete() .. worked ok for me

```
🌴 NatGateways set to nat-09819344f58f0f25d	nat-0233a53d67ead7559	nat-0e61955b31d12663f
{
    "NatGatewayId": "nat-09819344f58f0f25d"
}
 -> delete_nat_gateways [ nat-09819344f58f0f25d ] OK
{
    "NatGatewayId": "nat-0233a53d67ead7559"
}
 -> delete_nat_gateways [ nat-0233a53d67ead7559 ] OK
{
    "NatGatewayId": "nat-0e61955b31d12663f"
}
 -> delete_nat_gateways [ nat-0e61955b31d12663f ] OK
 -> wait_for_nat_gateway_delete [ nat-09819344f58f0f25d	nat-0233a53d67ead7559	nat-0e61955b31d12663f ] OK
 -> release_eips [ 13.213.218.135, eipalloc-0e4323c5e5d73f962 ] OK
 -> release_eips [ 18.138.17.110, eipalloc-049d967bf6548ac67 ] OK
 -> release_eips [ 54.179.27.52, eipalloc-0fc4279689ae484ae ] OK
```
