### ISSUE TITLE
Wait for API/router availability?

### ISSUE THREAD

**Issue by cuppett** [eformat/sno-for-100#7]
I'm getting faster at these automated steps.... :)

At the end of the scripts, they exit right after restart. I wonder if it couldn't wait for the API to be available or the instance to register active in the ELB?  (If it doesn't, moving right to the next step usually fails because it's not available.)

**Comment by eformat** [comment]
ok, i've added in wait_for_openshift_api and the line:

> It may take a couple of minutes for SNO to settle after restarting (authentication, ingress operators become available).

which is better .. could make it wait till you can login completely, but this is step in right direction

**Comment by eformat** [comment]
https://github.com/eformat/sno-for-100/blob/main/adjust-single-node.sh#L591-L608

**Comment by eformat** [comment]
OK .. waiting for API is better now 4 sure .. auth operator not always immediately available but better ...
