### ISSUE TITLE
openshift-install destroy cluster misses the EIP

### ISSUE THREAD

**Issue by cuppett** [eformat/sno-for-100#8]
After running this, you can easily run openshift-install destroy cluster and the instance + hosted zones + vpc get cleaned up. However, the new EIP from the conversion gets left behind. This is likely because there's only the sno-100 tag. 

If we copy the cluster tags from the instance and put it on the new EIP, I bet the openshift installer will help scrub that up when it tears it down.

**Comment by eformat** [comment]
ok added tagging to new EIP
